apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: elm-rs
  labels:
    app: elm-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elm-demo
  template:
    metadata:
      labels:
        app: elm-demo
    spec:
      containers:
      - name: elm-demo
        image: kobonaut/elm-demo:1.0.0
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
